agents:
    trae_agent:
        enable_lakeview: false
        model: test_model
        max_steps: 50
        tools:
            - bash
            - str_replace_based_edit_tool
            - sequentialthinking
            - task_done

model_providers:
    anthropic:
        api_key: sk-ant-test-key
        provider: anthropic

models:
    test_model:
        model_provider: anthropic
        model: test-model
        max_tokens: 1000
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 3
        parallel_tool_calls: true