agents:
    trae_agent:
        enable_lakeview: true
        lakeview_model: gpt-5-mini
        model: gpt-5
        max_steps: 50
        tools:
            - bash
            - str_replace_based_edit_tool
            - sequentialthinking
            - task_done

model_providers:
    openai:
        api_key: your-openai-api-key
        provider: openai

models:
    gpt-5:
        model_provider: openai
        model: gpt-5
        max_tokens: 16000
        temperature: 0.4
        top_p: 1
        max_retries: 3
        parallel_tool_calls: true
    gpt-5-mini:
        model_provider: openai
        model: gpt-5-mini
        max_tokens: 2000
        temperature: 0.3
        top_p: 1
        max_retries: 3
        parallel_tool_calls: true